### PR TITLE
Added Chinese (Simplified)

### PR DESCRIPTION
**Pull request by jy1263**

### CODE REVIEW

**Comment by jy1263** [comment]
aaaa sorry im sleep deprived, i meant to write (simplified) not (traditional)

**Comment by AndreasWebdev** [comment]
@jy1263 awesome! I'll let you know once the locale's for 1.0.0 are locked in

**Comment by jy1263** [comment]
okie thx!

**Comment by AndreasWebdev** [comment]
@jy1263 1.0.0 locale is now fixed, I'll close this because the codebase changed

**Pull request closed without merging**
