### PR TITLE
Added drag and drop notice/popup (triggers ondragenter)

### PR DESCRIPTION
**Pull request by jy1263**
Implemented a drag and drop popup (similar to the one when you drag a file into discord to upload) so it'll tell users that they can drag it in to the client. 
dragndropspinshare

### CODE REVIEW

**Comment by jy1263** [comment]
Kinda inspired by
dragndrop

**Comment by jy1263** [comment]
hmmm, but yea the styling of the popup is definitely not perfect yet tho, ill probs keep trying to tweak it and see what'll work

**Comment by AndreasWebdev** [comment]
You have to edit the less files or else your css will be overwritten after we change something.

**Comment by jy1263** [comment]
o okie thx for the notice

**Comment by AndreasWebdev** [comment]
Since it kinda conflicts with the current version, I'm gonna close it and throw your code in there in my local copy!

**Comment by jy1263** [comment]
okie nice (also beware its a lil messy)

**Pull request closed without merging**
